version: "3.9"

services:

  backend:
    build: .
    container_name: horaxhora-backend
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: horaxhora-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: horaxhora
    ports:
      - "5432:5432"
